// Test-only: PLAYWRIGHT_MODULE and PDFJS_MODULE point to installed test tools.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=path.resolve(__dirname,'..'),out=process.env.REMOK_TEST_OUTPUT||require('os').tmpdir();
(async()=>{
 const pdfjs=await import(process.env.PDFJS_MODULE||'pdfjs-dist/legacy/build/pdf.mjs');
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true}),page=await context.newPage(),errors=[];
 await context.route('**/*',route=>{const u=new URL(route.request().url()),name=u.pathname.split('/').pop();const pdf=name==='jspdf.umd.min.js',asset=/remok-(estimator|settings)-v2\.(css|js)$/.test(name);const file=pdf?(process.env.JSPDF_PATH||path.join(base,'../js/vendor',name)):path.join(base,asset?name:'calculator-v2.html');let body=fs.readFileSync(file,'utf8');if(!pdf&&!asset)body='<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body>'+body+'</body></html>';return route.fulfill({contentType:pdf||name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html; charset=utf-8',body});});
 page.on('pageerror',e=>errors.push(String(e)));await page.goto('https://remok.test/calc');
 await page.evaluate(()=>{
  const s=Remok.storage.read('estimate'),part=()=>({enabled:false,depth:'',type:'',depthChecked:false,hasDepthDifference:false,comment:''});
  const item=i=>({id:'p'+i,number:i,room:'Помещение №'+i+' — '+('длинное название помещения '.repeat(i===1?8:1)),mode:'glazing',productType:'triple',width:2100,height:1450,profile:'veka',lamination:'two',hardware:'Стандартная',sections:[{widthMm:700,openingType:'fixed'},{widthMm:700,openingType:'turn'},{widthMm:700,openingType:'tilt_turn'}],exterior:part(),interior:part()});
  s.items=Array.from({length:22},(_,i)=>item(i+1));
  Object.assign(s.items[1],{mode:'balcony-glazing',balconyGlazingMaterial:'aluminum',balconyGlazingShape:'u',sidePosition:'right',aluminumColor:'color',planes:['left','facade','right'].map(id=>{const p={...Remok.v2.newPlane(id),widthMm:6400,heightMm:2500,sectionCount:8,heightMode:'floor',upperHeightMm:1500,lowerHeightMm:1000,lowerFilling:'sandwich'};Remok.v2.equalPlane(p);p.sections.forEach(s=>s.openingType='sliding');return p;})});
  Object.assign(s.items[2],{productType:'balcony_small',geometryVersion:2,windowWidthMm:1400,windowHeightMm:1500,doorWidthMm:700,doorHeightMm:2200,doorSide:'right',sections:[{openingType:'turn'},{openingType:'tilt_turn'}]});
  s.items.forEach(p=>Remok.v2.sync(p,Remok.storage.pricing()));s.client={name:'Иванов Иван',phone:'+7 999 123-45-67',address:'Объект с длинным адресом '+('улица Тестовая, корпус второй '.repeat(5)),contactPreference:'telegram',telegramUsername:'@PRIVATE_NOT_IN_PDF'};s.step='document';s.discountMode='percent';s.discount=10;Remok.storage.write('estimate',s);
 });
 await page.reload();const event=page.waitForEvent('download');await page.locator('[data-action="download-pdf"]').click();await (await event).saveAs(path.join(out,'remok-v2-long.pdf'));
 const doc=await pdfjs.getDocument({data:new Uint8Array(fs.readFileSync(path.join(out,'remok-v2-long.pdf')))}).promise;
 let text='',vectors=0;for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),vp=p.getViewport({scale:1}),c=await p.getTextContent(),ops=await p.getOperatorList();assert(Math.abs(vp.width-595.28)<1);assert(Math.abs(vp.height-841.89)<1);vectors+=ops.fnArray.filter(n=>n===pdfjs.OPS.constructPath).length;for(const t of c.items){text+=t.str+' ';if(t.str.trim()){assert(t.transform[4]>=40,'left clip '+t.str);assert(t.transform[4]+t.width<558,'right clip '+t.str);assert(t.transform[5]>15&&t.transform[5]<815,'vertical clip '+t.str);}}}
 assert(doc.numPages>=20);assert(vectors>100);for(const t of ['КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ','Монтаж с расходными материалами','Окно 1: 1400','Дверь: 700','3,64','Сэндвич-панель','Раздвижная','5407978699','info@remok.net'])assert(text.includes(t),t);assert(!text.includes('@PRIVATE'));assert(!text.includes('sandwichAdjustment'));assert(!text.includes('�'));console.log('PASS: PDF',doc.numPages,'A4 pages;',vectors,'vector path operations; Cyrillic, long names, eight sliding sections, three planes, block dimensions, discount, company, private fields excluded, text bounds.');await doc.destroy();
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:()=>Promise.reject(new DOMException('cancel','AbortError'))})});await page.locator('[data-action="share-pdf"]').click();await page.waitForFunction(()=>document.querySelector('#remok-pdf-status').textContent.includes('Отправка отменена'));
 await page.evaluate(()=>{Object.defineProperty(navigator,'userAgent',{configurable:true,value:'iPhone'});Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false});window.open=()=>null;});await page.locator('[data-action="share-pdf"]').click();assert((await page.locator('#remok-pdf-status a').getAttribute('href')).startsWith('blob:'));
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:()=>Promise.reject(new DOMException('denied','NotAllowedError'))});window.open=()=>{throw Error('No delayed popup')};});await page.locator('[data-action="share-pdf"]').click();await page.waitForFunction(()=>!document.querySelector('[data-action="share-pdf"]').disabled);assert(await page.locator('#remok-pdf-status a').count());
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: Share cancel, iOS blocked popup and rejected-share fallback.');
})().catch(e=>{console.error(e);process.exit(1)});
